<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\LoginController as AuthLoginController;
use App\Http\Controllers\automController;
use App\Http\Controllers\CadetesPackController;
use App\Http\Controllers\Controller_QRgenerator;
use App\Http\Controllers\ControllerPackets;
use App\Http\Controllers\ControllerAsignar;
use App\Http\Controllers\UserAdminController;
use App\Http\Controllers\checkPackController;
use App\Http\Controllers\ClientesPackController;
use App\Http\Controllers\IntegracionController;
use App\Http\Controllers\editCadeteController;
use App\Http\Controllers\editClienteController;
use App\Http\Controllers\editListController;
use App\Http\Controllers\infoPackMeliController;
use App\Http\Controllers\ControllerPrice;
use App\Http\Controllers\savePackController;
use App\Http\Controllers\WebhookOrdersController;
use App\Http\Controllers\WebhookPriceController;
use App\Http\Controllers\Controller_TN_sticker;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\Auth\ForgotPasswordController;
use Illuminate\Support\Facades\Auth;

Route::get('/', [AuthLoginController::class,'ingreso'])->name('login');
Route::post('/',[AuthLoginController::class,'authenticate']);
Route::get('admin/', [AuthLoginController::class,'ingreso'])->name('login_admin');
Route::post('admin/',[AuthLoginController::class,'authenticate']);
Route::get('cadetes/', [AuthLoginController::class,'ingreso'])->name('login_cadete');
Route::post('cadetes/', [AuthLoginController::class,'authenticate']);
Route::get('/cadetes/desk_cadete',[CadetesPackController::class,'mostrarenvios'])->middleware('auth:cadetes')->name('desk_cadete');
Route::get('/logout',[AuthLoginController::class,'logout'])->name('logout');
Route::get('integracion', [IntegracionController::class,'Integracion'])->name('integracion');
Route::get('integracion/MELI', [IntegracionController::class,'IntegrarMELI'])->name('integrar_MELI');
Route::post('integracion/MELI', [IntegracionController::class,'IntegrarMELI_respu']);
Route::get('integracion/NUBE', [IntegracionController::class,'descarga_manual'])->name('integrar_NUBE');
Route::get('integracion/NUBE_autoriz', [IntegracionController::class,'integrarTiendaNube'])->name('NUBE_autoriz');
Route::post('integracion/NUBE_autoriz', [IntegracionController::class,'IntegrarNube_respu']);
//Route::get('integracion/hatty', [IntegracionController::class,'hatty']);
Route::get('/admin/logged_packets',[ControllerPackets::class,'mostrarenvios'])->middleware('auth:administ')->name('mostrarenvios');
Route::post('/admin/logged_packets',[ControllerPackets::class,'crearlista'])->middleware('auth:administ'); 
Route::post('/admin/logged_packets/update_TN',[ControllerPackets::class,'update_TN'])->middleware('auth:administ');
Route::get('/admin/assign_packets',[ControllerAsignar::class,'ingresoGet'])->middleware('auth:administ')->name('asignar');
Route::post('/admin/assign_packets',[ControllerAsignar::class,'AsignarPost'])->middleware('auth:administ');
Route::get('/admin/QRgenerator/{tag}',[Controller_QRgenerator::class, 'generarQR'])->middleware('auth:administ')->name('Genera_QR');
Route::get('/admin/Sticker_TN/{shipnum}',[Controller_TN_sticker::class, 'generar_sticker_TN'])->middleware('auth:administ')->name('Genera_sticker_TN');
Route::get('/admin/user_admin',[UserAdminController::class,'mostrarAdmin'])->middleware('auth:administ')->name('mostrarAdmin');
Route::post('/admin/user_admin',[UserAdminController::class,'borrarAdmin'])->middleware('auth:administ');
Route::get('/admin/add_admin',[UserAdminController::class,'formuAddAdmin'])->middleware('auth:administ')->name('formuAddAdmin');
Route::post('/admin/add_admin',[UserAdminController::class,'someterAdmin'])->middleware('auth:administ');
Route::get('/admin/check_ingresado',[checkPackController::class,'check'])->middleware('auth:administ')->name('checkearIngreso');
Route::get('/admin/show_cadete',[editCadeteController::class,'mostrar'])->middleware('auth:administ')->name('mostrarCadete');
Route::post('/admin/show_cadete',[editCadeteController::class,'delet_cadete'])->middleware('auth:administ');
Route::get('/admin/include_cadete',[editCadeteController::class,'planilla_cadete'])->middleware('auth:administ')->name('registrarCadete');
Route::post('/admin/include_cadete',[editCadeteController::class,'registrar_cadete'])->middleware('auth:administ');
Route::get('/admin/edit_cadete',[editCadeteController::class,'editar'])->middleware('auth:administ')->name('editarCadete');
//Route::post('/admin/edit_cadete',[editCadeteController::class,'delet_cadete'])->middleware('auth:administ');
Route::get('/admin/show_list',[editListController::class,'mostrar'])->middleware('auth:administ')->name('mostrarListas');
Route::post('/admin/show_list',[editListController::class,'delet_lista'])->middleware('auth:administ');
Route::get('/admin/include_packets',[ControllerPackets::class,'include_packets'])->middleware('auth:administ')->name('incluirEnvio');
Route::get('/admin/edit_client',[editClienteController::class,'mostrar'])->middleware('auth:administ')->name('infoCliente');
Route::post('/admin/edit_client',[editClienteController::class,'delet_client'])->middleware('auth:administ');
Route::get('/admin/add_client',[editClienteController::class,'agregar_get'])->middleware('auth:administ')->name('agregarCliente');
Route::post('/admin/add_client',[editClienteController::class,'agregar_post'])->middleware('auth:administ');
Route::get('/admin/name_client',[editClienteController::class,'planilla_cliente'])->middleware('auth:administ')->name('name_client');
Route::post('/admin/name_client',[editClienteController::class,'ActualizarCliente'])->middleware('auth:administ');
Route::get('/admin/info_packets/',[infoPackMeliController::class,'info_packets_get'])->middleware('auth:administ')->name('info_packets');
Route::post('/admin/info_packets/',[infoPackMeliController::class,'info_packets_post'])->middleware('auth:administ');
Route::get('/admin/update_packets',[ControllerPackets::class,'mostrarUpdate'])->middleware('auth:administ')->name('mostrarUpdate');
Route::post('/admin/update_packets',[ControllerPackets::class,'post_update'])->middleware('auth:administ'); 
Route::get('/admin/include_packs_gitt',[ControllerPackets::class,'include_packs_gitt_adm'])->middleware('auth:administ')->name('incluirEnvioGitt');
Route::post('/admin/include_packs_gitt',[savePackController::class,'save_pack_gitt'])->middleware('auth:administ');
Route::post('/admin/save_packet',[savePackController::class,'save_pack'])->middleware('auth:administ'); 
Route::post('/admin/save_packets_u',[savePackController::class,'save_pack_actua'])->middleware('auth:administ');
Route::get('/admin/price_packets',[ControllerPrice::class,'mostrarPrecios'])->middleware('auth:administ')->name('mostrarprecio');
Route::post('/admin/price_packets',[ControllerPrice::class,'actualizarPrecios'])->middleware('auth:administ');
Route::post('/admin/delete_packet',[savePackController::class,'delete_pack'])->middleware('auth:administ')->name('borrar');
Route::get('/clientes/logged_packets',[ClientesPackController::class,'mostrarenvios'])->middleware('auth:clientes')->name('mostrarenvios_cientes');
Route::get('/clientes/grant_permission',[IntegracionController::class,'otorgarPermiso'])->middleware('auth:clientes')->name('grant_permission');
Route::get('/clientes/include_packs_gitt',[ControllerPackets::class,'include_packs_gitt_cli'])->middleware('auth:clientes')->name('incluirEnvioGittCli');
Route::post('/clientes/include_packs_gitt',[savePackController::class,'save_pack_gitt'])->middleware('auth:clientes');
Route::post('/clientes/cancel_gitt',[savePackController::class,'cancel_client'])->middleware('auth:clientes')->name('cancel_gitt');
Route::get('/clientes/Sticker_TN/{shipnum}',[Controller_TN_sticker::class, 'generar_sticker_TN'])->middleware('auth:clientes')->name('Genera_sticker_TN_clientes');
Route::get('/clientes/Sticker_day',[Controller_TN_sticker::class, 'etiqueta_dia'])->middleware('auth:clientes')->name('etiqueta_dia');
Route::get('/forgot-password', [ResetPasswordController::class, 'ingreseEmail'])->name('password.email');
Route::post('/forgot-password', [ForgotPasswordController::class, 'sendResetLinkEmail']);
Route::get('/update-password', [ResetPasswordController::class, 'showResetForm'])->name('password.reset');
Route::post('/update-password', [ResetPasswordController::class, 'reset']);
//Route::get('/admin/prueba',[infoPackMeliController::class,'ruta_prueba'])->middleware('auth:administ'); 
//Route::get('/admin/prueba_actua',[ControllerPackets::class,'prueba_actua'])->middleware('auth:administ'); 
Route::get('/lkdmflksdflkewfl7d/kdmmdf7d5',[automController::class,'automatico']);
Route::post('/webhook/price',[WebhookPriceController::class,'RetrivePrice']);
Route::get('/webhook/notify_orders',[WebhookOrdersController::class,'recibirOrden']);
//////
//Route::get('creartester/', [testerController::class,'generar']);

